### PR TITLE
Fixed #48 - Enhanced the readability of docs

### LINKED ISSUE #48: fix: Inconsistency in documnetation text
### Is your feature request related to a problem? Please describe

The problem is that the information in the documents is not consistent. We need to fix this so that everyone can easily read and understand the documents.

Request Parameters on another page:

### Describe the solution you'd like

I want to standardize the documentation text by making key points and headings bold for better visibility and importance. Additionally, I'd like to use text boxes to highlight subpoints, improving readability. 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by Devmoni**
Fixed #48 

The documentation text has been improved by making key points and headings bold for better visibility and importance. Additionally, text boxes have been utilized to highlight subpoints, enhancing readability.

Before :

After:

### CODE REVIEW

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
Thanks for investing what was undoubtedly a lot of time with this code change (or maybe you did a find-and-replace 🤷)

Either way, I am open to this change but please:

1. Remove the extra newlines in index.js and index.css
2. Modify the site's CSS instead of manually bolding every element. https://tailwindcss.com/docs/font-weight
3. revert yarn.lock or explain why it changed

thanks!

**Comment by Devmoni** [comment]
Thank you very much for your guidance. I will proceed with making the required adjustments as per your instructions.

**Comment by Devmoni** [comment]
@aaronbrethorst Sir, I need your help with this PR.

 I've attempted to apply Tailwind to Markdown files, but I've found that I need to use HTML tags in each file. 

Additionally, I've added borders to the small headings in the Markdown files, but I'm unable to find a direct way to achieve this using Tailwind.

 Not everywhere backticks are applied to make a border. 

Could you please guide me on how to achieve this?

**Comment by aaronbrethorst** [comment]
@Devmoni sorry but I don't have enough free time to help you with your PR. If you won't be able to complete it, I recommend closing the PR.

**Comment by aaronbrethorst** [comment]
#105 took care of the last parts of this.

**Pull request closed without merging**
