### PR TITLE
fixed bug scrollbar sync with light/dark mode

### PR DESCRIPTION
**Pull request by Ajay9330**
#### Description:
fixing the minor issue #114 that is sync scrollbar with light and dark mode 

#### Changes done:
- [x] changed the index.css file

#### Screenshots/Videos
image
image

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Tried squashing the commits into one

### CODE REVIEW

**Comment by Ajay9330** [comment]
@aaronbrethorst please check this
i'm also getting this same issue with the ace editor but not got efficient solution, but try to fix that also in future commits will fully solving the problem

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
looks good but there's a merge conflict.

**Comment by Ajay9330** [comment]
Ok sir, I'll try to resolve the conflict, ASAP

**Comment by Ajay9330** [comment]
conflict-resolve but unable to squash the commits

**Comment by aaronbrethorst** [comment]
1. Always use a branch instead of working off your own `main` branch
2. `git rebase -i main`
3. Change `pick`s 2-n to `squash`

**Review by aaronbrethorst — APPROVED** [review]
👍

**Comment by Ajay9330** [comment]
Thank You sir,
I first time tried to rebase get little bit afraid of nano/vim editor!,
but now i got it! and preserve main branch because it is main

**Pull request merged**
