### PR TITLE
refactor:  Made the links displayed on the screen visually appealing.

### PR DESCRIPTION
**Pull request by ankitkumar748846**
Made the links displayed on the screen visually appealing.

After:

### CODE REVIEW

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
thanks for taking a stab at this, but I don't think this is the direction that this feature should go. Instead, what I'd like to see is:

1. Change `.xml` file extensions to `.json`
2. Make each URL into a link
3. Validate that all of the links work as expected.

**Comment by ankitkumar748846** [comment]
Okay sir

**Comment by ankitkumar748846** [comment]
@tarunsinghofficial  @aaronbrethorst   Yes, I am working on this issue.

**Comment by aaronbrethorst** [comment]
This was addressed in #64

**Pull request closed without merging**
