### PR TITLE
Add scrollbar styles for light and dark modes

### LINKED ISSUE #71: Feature: Enhance the scrollbar according to docs theme
### Is your feature request related to a problem? Please describe

The current scrollbars in the docs don't look good or match the docs theme. To achieve the desired visual consistency and aesthetics across our project, I would like to enhance them across the whole site.

### Describe the solution you'd like

Enhancing the scrollbar in the entire docs to the matched theme i.e., dark colors for now.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by tarunsinghofficial**
#### Description:

The current scrollbars in the docs don't look good or match the docs theme. To achieve the desired visual consistency and aesthetics across our project, I would like to enhance them across the whole site.

#### Issue fixed:

Enhancing the scrollbar in the entire docs to the matched theme i.e., dark colors for now.

Fixes #71 

#### Changes done:
- [x] Task 1

#### Screenshots/Videos

Before:
image

After:
image

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Tried squashing the commits into one

### CODE REVIEW

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
this is definitely an improvement, but I see one regression that I want fixed: on a Mac with a trackpad, the scrollbars only appear when actively scrolling. That is no longer the case with this PR, and I'd like that contingency handled.

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
great work; there's a merge conflict with index.css that will need to be fixed before merging though.

**Comment by tarunsinghofficial** [comment]
> great work; there's a merge conflict with index.css that will need to be fixed before merging though.

Got it. Resolved the conflicts.

**Review by aaronbrethorst — APPROVED** [review]
👍

**Pull request merged**
