### PR TITLE
docs: Change in documentation of Readme

### PR DESCRIPTION
**Pull request by ankitkumar748846**
fix: #32 
This Readme  file will provide users with essential information about the organization, its contributors, and how to set up the software on different platforms.

### CODE REVIEW

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
this will need to be revised as the README has changed. Also, I don't think this is a big enough project yet to need the set of labels described in `contributing.md`. Later on, I think this could be useful, but it doesn't make sense here now.

**Comment by ankitkumar748846** [comment]
Thank you for bringing this to my attention. I completely understand your perspective. Since the project is still in its early stages and might not require a comprehensive set of labels, we can definitely revisit the need for them as the project evolves.

Regarding the revision of the README, could you please provide more details on the changes made? This will help ensure that the README accurately reflects the current state of the project.

**Comment by ankitkumar748846** [comment]
@aaronbrethorst  solved the merge conflict.

**Comment by aaronbrethorst** [comment]
I don't think this makes sense to merge at this time. Maybe _just_ the contributing guide if it is stripped down as I mentioned before. But there's not a ton of content in the README at this time, and splitting it into three files just complicates the learning process for prospective contributors.

**Pull request closed without merging**
