### PR TITLE
Fix external links to open in new tab

### PR DESCRIPTION
**Pull request by jiya-singhal**
resolved issue #139 

Description:
This pull request updates the external links on the bottom of the page to open in a new tab. The change involves adding the target="_blank" attribute to anchor tags linking to GitHub, the App Store, the Play Store, and the Open Transit Software Foundation. This enhancement ensures that when users click on these external links, they are directed to the respective sites in a new browser tab, preserving their current session on the application.

Changes Made:

Added target="_blank" to the GitHub link.
Added target="_blank" to the App Store link.
Added target="_blank" to the Play Store link.
Added target="_blank" to the Open Transit Software Foundation link.
Motivation:
Opening external links in a new tab prevents users from leaving the current application session, providing a better user experience by maintaining the context of the original page.

Testing:
The changes were manually tested to verify that all external links now open in a new tab. No other parts of the application were affected by these changes.

Checklist:

 Added target="_blank" to external links
 Manually tested the changes
 Verified that the change does not impact other parts of the application

[Screencast from 06-08-24 09:37:47 PM IST.webm](https://github.com/user-attachments/assets/fad96563-dfc4-41ab-a0c5-88f7c8f3e81d)

### CODE REVIEW

**Comment by jiya-singhal** [comment]
Respected projects maintainers 

I've updated the external links on the bottom of the page to open in a new tab, as discussed. The changes include adding target="_blank" to the relevant links to ensure users are not navigated away from the application.

Could someone please review the changes and provide feedback? Your input would be greatly appreciated.

Thank you!

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
thank you! Before I can merge this, though, I will need you to please revert all changes that are unrelated to the issue you're resolving.

**Comment by jiya-singhal** [comment]
Hi @aaronbrethorst,

As requested, I have reverted the unrelated changes. The pull request now focuses solely on the issue of external links opening in a new tab.
Could you please review the updated code?

Thank you!

**Review by aaronbrethorst — APPROVED** [review]
looks great, thank you!

**Pull request merged**
