### PR TITLE
feat: dockerization for development environment

### PR DESCRIPTION
**Pull request by ankitkumar748846**
#### Changes done:
- [x] Task 1

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Tried squashing the commits into one

### CODE REVIEW

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
The Dockerfile isn't in the right location

```
➜  onebusaway-docs git:(docker) docker-compose up
[+] Building 0.1s (2/2) FINISHED                                                                                   docker:desktop-linux
 => [web internal] load build definition from Dockerfile                                                                           0.0s
 => => transferring dockerfile: 2B                                                                                                 0.0s
 => [web internal] load .dockerignore                                                                                              0.0s
 => => transferring context: 517B                                                                                                  0.0s
failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3718995953/Dockerfile: no such file or directory
```

**Comment by ankitkumar748846** [comment]
sir due to some error the Dockerfile was moved to wrong folder while committing ... i fixed the issue and also added setup guide for windows, mac & linux ... please let me if any other changes are required.

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
thanks for persevering on this! I'm seeing an error when the container launches related to esbuild and yarn. Not sure exactly what's going on, but for reference I'm using a Mac with an M1 CPU.

```
web-1  | [Frontend] yarn run esbuild-dev
web-1  | [Frontend] yarn run v1.22.19
web-1  | [Frontend] $ node esbuild.config.js --watch
web-1  | [Frontend] /app/node_modules/esbuild/lib/main.js:1910
web-1  | [Frontend]           throw new Error(`
web-1  | [Frontend]                 ^
web-1  | [Frontend] 
web-1  | [Frontend] Error: 
web-1  | [Frontend] You installed esbuild for another platform than the one you're currently using.
web-1  | [Frontend] This won't work because esbuild is written with native code and needs to
web-1  | [Frontend] install a platform-specific binary executable.
web-1  | [Frontend] 
web-1  | [Frontend] Specifically the "@esbuild/darwin-arm64" package is present but this platform
web-1  | [Frontend] needs the "@esbuild/linux-arm64" package instead. People often get into this
web-1  | [Frontend] situation by installing esbuild on Windows or macOS and copying "node_modules"
web-1  | [Frontend] into a Docker image that runs Linux, or by copying "node_modules" between
web-1  | [Frontend] Windows and WSL environments.
web-1  | [Frontend] 
web-1  | [Frontend] If you are installing with npm, you can try not copying the "node_modules"
web-1  | [Frontend] directory when you copy the files over, and running "npm ci" or "npm install"
web-1  | [Frontend] on the destination platform after the copy. Or you could consider using yarn
web-1  | [Frontend] instead of npm which has built-in support for installing a package on multiple
web-1  | [Frontend] platforms simultaneously.
web-1  | [Frontend] 
web-1  | [Frontend] If you are installing with yarn, you can try listing both this platform and the
web-1  | [Frontend] other platform in your ".yarnrc.yml" file using the "supportedArchitectures"
web-1  | [Frontend] feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
web-1  | [Frontend] Keep in mind that this means multiple copies of esbuild will be present.
web-1  | [Frontend] 
web-1  | [Frontend] Another alternative is to use the "esbuild-wasm" package instead, which works
web-1  | [Frontend] the same way on all platforms. But it comes with a heavy performance cost and
web-1  | [Frontend] can sometimes be 10x slower than the "esbuild" package, so you may also not
web-1  | [Frontend] want to do that.
web-1  | [Frontend] 
```

**Comment by aaronbrethorst** [comment]
I'm going to close this PR. Feel free to reopen once the issue noted above has been fixed.

**Pull request closed without merging**
